### PR TITLE
Hardware buttons support

### PR DESCRIPTION
**Pull request by SunboX**

### CODE REVIEW

**Comment by janjongboom** [comment]
Thanks for the patch, quick question (please ping me on email or IRC (janjongboom @ irc.mozilla.org, #gaia or #b2g), up until latest release the mozChromeEvent code is still there, it has not been removed in favor of the keydown / keyup event. Shouldn't be easier to just keep using that?

**Comment by SunboX** [comment]
I did write a mail to janjongboom [at] irc.mozilla.org but that seem not to work well. ;) Here's what I wrote (main part):

looks like nothing will happen by now, but in future the mozChromeEvent will be removed.
Here's a wiki page about it:

https://wiki.mozilla.org/WebAPI/BrowserAPI/KeyboardEvent#Dispatch_KeyboardEvent_across_BrowserElements
**Part 3 - Remove all translated low-level input events**
_In this part, we need to refactor both hardware_buttons.js and software_button_manager.js to remove all low-level input event names. In software_button_manager.js, we should dispatch events the same as new key event (such as mozbrowserbeforekeydown or keydown...etc)_

If you ask me, we should keep both events. mozChromeEvent for those who flash Jan.OS on older devices and the new hardware key events to be ready for future ones.

**Comment by janjongboom** [comment]
Interesting, yeah my IRC name at the irc.mozilla.org IRC server is janjongboom. E-mail is janjongboom@gmail.com :-)

But yeah if there's already a new permission being added for it I'm tempted to take this patch. I'll rework it so it's part of the documentation, rather than the _test file.

Thanks

**Comment by SunboX** [comment]
great, thanks a lot! :+1:

**Comment by janjongboom** [comment]
I decided to land this in the docs instead. The API is pretty straightforward, you can now do window.addEventListener('keydown') and the key is Power/VolDown/VolUp, pretty easy.

**Comment by SunboX** [comment]
That's ok for me. :) Thanks!

**Pull request closed without merging**
